// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int N = Integer.parseInt(args[0]);
	int biggerThanHalf = 0; 
	int smallerThanHalf =0;
	for (int i = 0; i < N; i++) {
		if (Math.random()>0.5){
			biggerThanHalf = biggerThanHalf +1; }
		else{ smallerThanHalf = smallerThanHalf +1;}}

		double ratio = 0; 
		if (biggerThanHalf>smallerThanHalf){
			ratio = (double)smallerThanHalf/(double)biggerThanHalf;}
			else{ratio = (double)biggerThanHalf/ (double)smallerThanHalf;}

		System.out.println("> 0.5: " + biggerThanHalf + " times");
		System.out.println("< 0.5: " + smallerThanHalf + " times");
		System.out.println("Ratio: " + ratio);

	
	}
}
